version: '3.8'

services:
  shurull_api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILDKIT_INLINE_CACHE: 1
    container_name: shurull_api_staging
    ports:
      - "5001:5000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - PROMETHEUS_MULTIPROC_DIR=/tmp
      - ENVIRONMENT=staging
      - DOCKER_BUILDKIT=1
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  prometheus_staging:
    image: prom/prometheus
    container_name: shurull_prometheus_staging
    ports:
      - "9091:9090"
    volumes:
      - ./prometheus.staging.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana_staging:
    image: grafana/grafana
    container_name: shurull_grafana_staging
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-admin}
      - GF_SERVER_ROOT_URL=https://grafana-staging.shurull-api.com
    volumes:
      - grafana-staging-storage:/var/lib/grafana

volumes:
  grafana-staging-storage: