global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'api-platform'
    static_configs:
      - targets: ['api:5000']

  - job_name: 'deployed-apis'
    static_configs:
      - targets: ['api:5000']
    metrics_path: '/metrics'
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance