global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'api-platform'
    static_configs:
      - targets: ['shurull_api:5000']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
